path: .
train: data/additional_splits/train.txt
val: data/additional_splits/val.txt
nc: 118
names:
- 마그밀정(수산화마그네슘)
- 게보린정 300mg/PTP
- 알마겔정(알마게이트)(수출명:유한가스트라겔정)
- 보령부스파정 5mg
- 뮤테란캡슐 100mg
- 일양하이트린정 2mg
- 기넥신에프정(은행엽엑스)(수출용)
- 무코스타정(레바미피드)(비매품)
- 동아오팔몬정(리마프로스트알파-시클로덱스트린포접화합물)
- 알드린정
- 뉴로메드정(옥시라세탐)
- 타이레놀정500mg
- 에어탈정(아세클로페낙)
- 비유피-4정 20mg
- 엘도스캡슐(에르도스테인)(수출용)
- 삼남건조수산화알루미늄겔정
- 프로스카정
- 타이레놀이알서방정(아세트아미노펜)(수출용)
- 삐콤씨에프정 618.6mg/병
- 조인스정 200mg
- 씨즈날정(세티리진염산염)
- 이튼큐정 35mg/PTP
- 쎄로켈정 100mg
- 넥시움정 40mg
- 동화덴스톨캡슐 150mg/PTP
- 아스피린프로텍트정 100mg
- 리렉스펜정 300mg/PTP
- 아빌리파이정 10mg
- 자이프렉사정 2.5mg
- 투스딘골드캡슐 150mg/PTP
- 다보타민큐정 10mg/병
- 이가탄에프캡슐 150mg/PTP
- 엘스테인캡슐(에르도스테인)
- 써스펜8시간이알서방정 650mg
- 에빅사정(메만틴염산염)(비매품)
- 한미탐스캡슐 0.2mg
- 엔테론정 150mg
- 아보다트연질캡슐 0.5mg
- 리피토정 20mg
- 카듀엣정 5mg/20mg
- 크레스토정 20mg
- 가바토파정 100mg
- 동아가바펜틴정 800mg
- 오마코연질캡슐(오메가-3-산에틸에스테르90)
- 란스톤엘에프디티정 30mg
- 리리카캡슐 150mg
- 종근당글리아티린연질캡슐(콜린알포세레이트) 
- 콜리네이트연질캡슐 400mg
- 트루비타정 60mg/병
- 스토가정 10mg
- 노바스크정 5mg
- 지르텍정(세티리진염산염)
- 라시도필캡슐(비매품)
- 마도파정
- 플라빅스정 75mg
- 자트랄엑스엘정 10mg
- 인사돌플러스정 35mg/PTP
- 베시케어정 10mg
- 엑스포지정 5/160mg
- 펠루비정(펠루비프로펜)
- 아토르바정 10mg
- 라비에트정 20mg
- 리피로우정 20mg
- 자누비아정 50mg
- 맥시부펜이알정 300mg
- 메가파워정 90mg/병
- 쿠에타핀정 25mg
- 비타비백정 100mg/병
- 디카맥스디플러스정
- 토비애즈서방정 4mg
- 놀텍정 10mg
- 액티프롤정 60mg/PTP
- 마이칼디정
- 자누메트정 50/850mg
- 큐시드정 31.5mg/PTP
- 아모잘탄정 5/100mg
- 클라리틴정(로라타딘)
- 원더칼-디츄어블정
- 세비카정 10/40mg
- 트윈스타정 40/5mg
- 카나브정 60mg
- 울트라셋이알서방정
- 졸로푸트정 100mg
- 플리바스정 50mg
- 트라젠타정(리나글립틴)
- 비모보정 500/20mg
- 레일라정
- 리바로정 4mg
- 디카테오정
- 렉사프로정 15mg
- 트라젠타듀오정 2.5/850mg
- 비오플250캡슐 282.5mg
- 낙소졸정 500/20mg
- 아질렉트정(라사길린메실산염)
- 자누메트엑스알서방정 100/1000mg
- 글리아타민연질캡슐
- 신바로정
- 트루패스정 4mg
- 에스원엠프정 20mg
- 브린텔릭스정 20mg
- 글리틴정(콜린알포세레이트)
- 제미메트서방정 50/1000mg
- 아토젯정 10/40mg
- 제라타딘정(로라타딘)
- 로수젯정10/5밀리그램
- 알바스테인캡슐(에르도스테인)
- 로수바미브정 10/20mg
- 엔트레스토필름코팅정 200mg
- 락토엔큐캡슐(바실루스리케니포르미스균) 
- 뮤코원캡슐(에르도스테인)
- 알러비정(세티리진염산염)
- 람노스캡슐500mg/병
- 카발린캡슐 25mg
- 바이오탑디캡슐 50mg/병
- 케이캡정 50mg
- 바이오탑하이캡슐 150mg/병
- 엘스테인정(에르도스테인)
- 디카테오엘씨정 10mg/병
