path: /Users/youuchul/Documents/github/03_projects/01_HealthEat Pill Detection Model/healtheat_vision/data/yolo
train: images/train
val: images/val
nc: 118
names:
  0: 마그밀정(수산화마그네슘)
  1: 게보린정 300mg/PTP
  2: 알마겔정(알마게이트)(수출명:유한가스트라겔정)
  3: 보령부스파정 5mg
  4: 뮤테란캡슐 100mg
  5: 일양하이트린정 2mg
  6: 기넥신에프정(은행엽엑스)(수출용)
  7: 무코스타정(레바미피드)(비매품)
  8: 동아오팔몬정(리마프로스트알파-시클로덱스트린포접화합물)
  9: 알드린정
  10: 뉴로메드정(옥시라세탐)
  11: 타이레놀정500mg
  12: 에어탈정(아세클로페낙)
  13: 비유피-4정 20mg
  14: 엘도스캡슐(에르도스테인)(수출용)
  15: 삼남건조수산화알루미늄겔정
  16: 프로스카정
  17: 타이레놀이알서방정(아세트아미노펜)(수출용)
  18: 삐콤씨에프정 618.6mg/병
  19: 조인스정 200mg
  20: 씨즈날정(세티리진염산염)
  21: 이튼큐정 35mg/PTP
  22: 쎄로켈정 100mg
  23: 넥시움정 40mg
  24: 동화덴스톨캡슐 150mg/PTP
  25: 아스피린프로텍트정 100mg
  26: 리렉스펜정 300mg/PTP
  27: 아빌리파이정 10mg
  28: 자이프렉사정 2.5mg
  29: 투스딘골드캡슐 150mg/PTP
  30: 다보타민큐정 10mg/병
  31: 이가탄에프캡슐 150mg/PTP
  32: 엘스테인캡슐(에르도스테인)
  33: 써스펜8시간이알서방정 650mg
  34: 에빅사정(메만틴염산염)(비매품)
  35: 한미탐스캡슐 0.2mg
  36: 엔테론정 150mg
  37: 아보다트연질캡슐 0.5mg
  38: 리피토정 20mg
  39: 카듀엣정 5mg/20mg
  40: 크레스토정 20mg
  41: 가바토파정 100mg
  42: 동아가바펜틴정 800mg
  43: 오마코연질캡슐(오메가-3-산에틸에스테르90)
  44: 란스톤엘에프디티정 30mg
  45: 리리카캡슐 150mg
  46: 종근당글리아티린연질캡슐(콜린알포세레이트) 
  47: 콜리네이트연질캡슐 400mg
  48: 트루비타정 60mg/병
  49: 스토가정 10mg
  50: 노바스크정 5mg
  51: 지르텍정(세티리진염산염)
  52: 라시도필캡슐(비매품)
  53: 마도파정
  54: 플라빅스정 75mg
  55: 자트랄엑스엘정 10mg
  56: 인사돌플러스정 35mg/PTP
  57: 베시케어정 10mg
  58: 엑스포지정 5/160mg
  59: 펠루비정(펠루비프로펜)
  60: 아토르바정 10mg
  61: 라비에트정 20mg
  62: 리피로우정 20mg
  63: 자누비아정 50mg
  64: 맥시부펜이알정 300mg
  65: 메가파워정 90mg/병
  66: 쿠에타핀정 25mg
  67: 비타비백정 100mg/병
  68: 디카맥스디플러스정
  69: 토비애즈서방정 4mg
  70: 놀텍정 10mg
  71: 액티프롤정 60mg/PTP
  72: 마이칼디정
  73: 자누메트정 50/850mg
  74: 큐시드정 31.5mg/PTP
  75: 아모잘탄정 5/100mg
  76: 클라리틴정(로라타딘)
  77: 원더칼-디츄어블정
  78: 세비카정 10/40mg
  79: 트윈스타정 40/5mg
  80: 카나브정 60mg
  81: 울트라셋이알서방정
  82: 졸로푸트정 100mg
  83: 플리바스정 50mg
  84: 트라젠타정(리나글립틴)
  85: 비모보정 500/20mg
  86: 레일라정
  87: 리바로정 4mg
  88: 디카테오정
  89: 렉사프로정 15mg
  90: 트라젠타듀오정 2.5/850mg
  91: 비오플250캡슐 282.5mg
  92: 낙소졸정 500/20mg
  93: 아질렉트정(라사길린메실산염)
  94: 자누메트엑스알서방정 100/1000mg
  95: 글리아타민연질캡슐
  96: 신바로정
  97: 트루패스정 4mg
  98: 에스원엠프정 20mg
  99: 브린텔릭스정 20mg
  100: 글리틴정(콜린알포세레이트)
  101: 제미메트서방정 50/1000mg
  102: 아토젯정 10/40mg
  103: 제라타딘정(로라타딘)
  104: 로수젯정10/5밀리그램
  105: 알바스테인캡슐(에르도스테인)
  106: 로수바미브정 10/20mg
  107: 엔트레스토필름코팅정 200mg
  108: 락토엔큐캡슐(바실루스리케니포르미스균) 
  109: 뮤코원캡슐(에르도스테인)
  110: 알러비정(세티리진염산염)
  111: 람노스캡슐500mg/병
  112: 카발린캡슐 25mg
  113: 바이오탑디캡슐 50mg/병
  114: 케이캡정 50mg
  115: 바이오탑하이캡슐 150mg/병
  116: 엘스테인정(에르도스테인)
  117: 디카테오엘씨정 10mg/병
